### ISSUE TITLE
Create an API route that contains Eigen settings

### ISSUE THREAD

**Issue by orta** [artsy/echo#1]
It could be something like: `/api/v1/eigen/app_settings`

Which right now contains three types of data, named routes, which is just a key-value between two strings. In-app strings, also a key-value string:string. Finally features, which allow us to hide features based on server-side flags. 

```
{
  "routes" : {
    "ARArtistRoute" : "/artist/:id",
    "ARProfileArtistRoute" : "/:profile_id/artist/:id",
    "ARArtworkRoute" : "/artwork/:id",
    "ARGeneRoute" : "/gene/:id",
    "ARShowRoute" : "/show/:id"
  },
  "strings" : {
    "intro_text" : "Artsy has xxx,yyy artworks"
  },
  "features" : {
    "ipad_vir" : false
  }
}
```

**Comment by dylanfareed** [comment]
@orta, I'd like to provide semantic labels for columns here. What would you call the type of thing that is `ARArtistRoute`?

**Comment by dylanfareed** [comment]
I'm on the fence about `strings` here. Feels like we may be better off with some system that supports i18n for this kind of app copy.

**Comment by dylanfareed** [comment]
Also, how do you feel about this being a hypermedia api?

**Comment by orta** [comment]
> , I'd like to provide semantic labels for columns here. What would you call the type of thing that is ARArtistRoute?

I've been calling it a RouteName

**Comment by orta** [comment]
> hypermedia

 ¯\_(ツ)_/¯ sounds nice enough, I know the roughs but this isn't a giant API with tonnes of things. It's meant to be a pretty lean settings json

**Comment by orta** [comment]
> I'm on the fence about strings here. Feels like we may be better off with some system that supports i18n for this kind of app copy.

This is way optimistic, the only thing I know of that's ready to deal with i8n is Folio. The iOS app has it's own native i8n stuff anyway, it's reasonable to assume that Eigen is english only for at least a year or so at this rate.

**Comment by dylanfareed** [comment]
Closing this in favor of some smaller more specific issues.

**Comment by dylanfareed** [comment]
https://github.com/artsy/echo/issues?q=is%3Aopen+is%3Aissue+milestone%3AMVP
